### ISSUE TITLE
StCTREncrypted.h:11-12: StCTREncrypted is a generic alg. May...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#100]
The puzzle `82-9efa52be` in [`kuznyechik/StCTREncrypted.h`](https://github.com/DronMDF/goost/blob/master/kuznyechik/StCTREncrypted.h) (lines 11-12) has to be resolved: "StCTREncrypted is a generic alg. May be share this code with magma with templates?"

The puzzle was created by Andrey Valyaev on 12-May-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Stream is deprecated concept
