### ISSUE TITLE
CPPLINT.cfg:2-2: enable build/include

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#114]
The puzzle `112-c412e6a9` in [`CPPLINT.cfg`](https://github.com/DronMDF/goost/blob/master/CPPLINT.cfg) (lines 2-2) has to be resolved: "enable build/include"

The puzzle was created by Andrey Valyaev on 19-May-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
No, this is wrong check, not detect local include...

**Comment by 0pdd** [comment]
The puzzle `112-c412e6a9` has disappeared from the source code, that's why I closed this issue.
