### ISSUE TITLE
CMakeLists.txt:23-23: Hardcoded shippable path

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#125]
The puzzle `122-7e6e9dd5` in [`test2o/CMakeLists.txt`](https://github.com/DronMDF/goost/blob/master/test2o/CMakeLists.txt) (lines 23-23) has to be resolved: "Hardcoded shippable path"

The puzzle was created by Andrey Valyaev on 30-Jun-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
This is actual
