### ISSUE TITLE
.travis.yml:22-22: Add style make target

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#136]
The puzzle `124-717d4f93` in [`.travis.yml`](https://github.com/DronMDF/goost/blob/master/.travis.yml) (lines 22-22) has to be resolved: "Add style make target"

The puzzle was created by Andrey Valyaev on 26-Jul-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Hm... make style target applied from 2out and work to entire goost project.
Live it.

**Comment by 0pdd** [comment]
The puzzle `124-717d4f93` has disappeared from the source code, that's why I closed this issue.
