### ISSUE TITLE
Iterator.h:12-12: Iterator::value() should return...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#214]
The puzzle `103-9cc10377` (from #103) in [`kuznyechik/Iterator.h`](https://github.com/DronMDF/goost/blob/master/kuznyechik/Iterator.h) (lines 12-12) has to be resolved: "Iterator::value() should return pointer to Block"

The puzzle was created by Andrey Valyaev on 14-Sep-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Iterator should be Block!

**Comment by DronMDF** [comment]
this is complete. i wait for fix bug in 0pdd.
