### ISSUE TITLE
ReprBlock.h:14-14: Add ctor to ReprBlock with imm values...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#241]
The puzzle `234-45d91106` (from #234) in [`test2o/kuznyechik/ReprBlock.h`](https://github.com/DronMDF/goost/blob/master/test2o/kuznyechik/ReprBlock.h) (lines 14-14) has to be resolved: "Add ctor to ReprBlock with imm values for short tests"

The puzzle was created by Andrey Valyaev on 18-Sep-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
This is not actual, after TestBlockEqual.
Need to remove this from code.

String better represent over ReprString. This are doing in TestBlockEqual.

**Comment by 0pdd** [comment]
The puzzle `234-45d91106` has disappeared from the source code, that's why I closed this issue.
