### ISSUE TITLE
Key.h:17-18: magma::Key used in two direction...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#328]
The puzzle `274-07e26fdb` (from #274) in [`magma/Key.h`](https://github.com/DronMDF/goost/blob/master/magma/Key.h) (lines 17-18) has to be resolved: "magma::Key used in two direction forward and backward. we need two classes implement Forward and Backward transformed block."

The puzzle was created by Andrey Valyaev on 06-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
This is done.

**Comment by 0pdd** [comment]
The puzzle `274-07e26fdb` has disappeared from the source code, that's why I closed this issue.
