### ISSUE TITLE
StCTREncryptedTest.cpp:19-19: introduce kuznyechik::ReprStream for...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#329]
The puzzle `323-db6ce2bd` (from #323) in [`test2o/kuznyechik/StCTREncryptedTest.cpp`](https://github.com/DronMDF/goost/blob/master/test2o/kuznyechik/StCTREncryptedTest.cpp) (lines 19-19) has to be resolved: "introduce kuznyechik::ReprStream for testing"

The puzzle was created by Andrey Valyaev on 06-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Stream is deprecated conception
