### ISSUE TITLE
StMemory.cpp:33-33: Add size parameter to iterator, and...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#337]
The puzzle `332-5f83d6c3` (from #332) in [`magma/StMemory.cpp`](https://github.com/DronMDF/goost/blob/master/magma/StMemory.cpp) (lines 33-33) has to be resolved: "Add size parameter to iterator, and he can determine last() and size() for youself."

The puzzle was created by Andrey Valyaev on 08-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Stream is deprecated conception, need to remove StMemory.
