### ISSUE TITLE
ImitedBlock.h:15-15: ImitedBlock should be Block

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#357]
The puzzle `352-8b74b035` (from #352) in [`gost89/ImitedBlock.h`](https://github.com/DronMDF/goost/blob/master/gost89/ImitedBlock.h) (lines 15-15) has to be resolved: "ImitedBlock should be Block"

The puzzle was created by Andrey Valyaev on 16-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Block is deprecated conception
