### ISSUE TITLE
ImitedBlock.h:17-17: ImitedBlock should named BlkImited

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#358]
The puzzle `352-471ba5f3` (from #352) in [`gost89/ImitedBlock.h`](https://github.com/DronMDF/goost/blob/master/gost89/ImitedBlock.h) (lines 17-17) has to be resolved: "ImitedBlock should named BlkImited"

The puzzle was created by Andrey Valyaev on 16-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Prefix namind conversion is wrong approach.
We don't use it.
