### ISSUE TITLE
RBlock.cpp:13-14: Use predefined gmul tab for speedup...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#84]
The puzzle `82-c44ff2af` in [`kuznyechik/RBlock.cpp`](https://github.com/DronMDF/goost/blob/master/kuznyechik/RBlock.cpp) (lines 13-14) has to be resolved: Use predefined gmul tab for speedup kuznyechik alg Calculation is slower solution.

The puzzle was created by Andrey Valyaev on 20-Apr-17. 

Estimate: 32 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by DronMDF** [comment]
This is an optimization... it's not goal of this project.

**Comment by DronMDF** [comment]
Not actual.
