### ISSUE TITLE
KeyIter.cpp:46-47: Cn is a const key. Need to predefine...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#85]
The puzzle `82-68bf8978` in [`kuznyechik/KeyIter.cpp`](https://github.com/DronMDF/goost/blob/master/kuznyechik/KeyIter.cpp) (lines 46-47) has to be resolved: Cn is a const key. Need to predefine this keys

The puzzle was created by Andrey Valyaev on 20-Apr-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by DronMDF** [comment]
No, this is a not effective.
More effectively - is a KeyIterCache for all KeyIter in Key.
