### ISSUE TITLE
CTREncryptedStreamTest.cpp:1-3: Class naming style is Ambiguous Need...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/goost#87]
The puzzle `82-b35f786e` in [`test/kuznyechik/CTREncryptedStreamTest.cpp`](https://github.com/DronMDF/goost/blob/master/test/kuznyechik/CTREncryptedStreamTest.cpp) (lines 1-3) has to be resolved: Class naming style is Ambiguous Need to use suffix extension for close proximity of related classes This applies to BlockStreams and Blocks

The puzzle was created by Andrey Valyaev on 20-Apr-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by DronMDF** [comment]
May be a can use prefixes?

BlockStream -> BsCTREncrypted, BsMemory
BlockValue -> BvEncrypted, BvDecrypted?

It's look nice...

**Comment by DronMDF** [comment]
Or

Stream -> StCTREncrypted StMemory StPadded
Value -> VaEncrypted 
Iterator -> ItCTREncrypted

Why do I always have the word Block?

**Comment by 0pdd** [comment]
The puzzle `82-b35f786e` has disappeared from the source code, that's why I closed this issue.
